services:
  # The Web Service for the user interface
  - type: web
    name: finance-summary-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --workers 2 --timeout 120 app:app"
    envVars:
      - fromGroup: finance-keys

  # The new Background Worker to process jobs
  - type: worker
    name: finance-summary-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - fromGroup: finance-keys

