services:
  # The Web Service for the user interface
  - type: web
    name: finance-summary-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --workers 2 --timeout 120 app:app"
    envVars:
      - fromGroup: finance-keys

  # The background job, configured to run as a Cron Job every minute
  - type: cron
    name: finance-summary-job-runner
    env: python
    schedule: "* * * * *" # This means "run every minute"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - fromGroup: finance-keys

